language: ruby
os:windows

branches:
  only:
    - master

notifications:
  email:
    on_success: always
    on_failure : always 

script:
 - gem update --system
 - gem install bundler
 - bundler update --bundler
 - gem install jekyll bundler
 - bundle exec jekyll build

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

